# -*- coding: utf-8 -*-
"""판다스연습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T7wa1z8ejyOC_v3RlmiKoojhmDIedJiM
"""

# print("코렙에 오신 것을 환영합니다.")
# 실행만! 컨트롤 + 엔터
# 실행하고 다음 입력할 화면 자동으로 만든다! 쉬프트 + 엔터

# print("나는 자동완성됩니다. tab 또는 ctrl + space bar")

# 하나 하나의 입력창: cell

# temp = "임시 데이터"
# temp

import requests

# !pip install bs4
from bs4 import BeautifulSoup

url = "https://finance.naver.com/item/main.nhn?code=028300"
url

site = requests.get(url)
site

content = BeautifulSoup(site.content, "html.parser")
content

no_today = content.find("p", {"class":"no_today"})
no_today

blind_now = no_today.find("span", {"class":"blind"})
blind_now

print("최종 결과값: ", blind_now.text)

