# -*- coding: utf-8 -*-
"""판다스 연습2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VUjy7fD2hI0sxE_BgKWS-zC5f3dbdk9A
"""

import pandas as pd

import numpy as np

dates = pd.date_range("2019-10-22", periods=6)
dates

# 데이터를 수집 한뒤 무조건 table형태로 만들어야 함

# 데이터를 분석하기 위한 기본적인 틀(데이터를 table형태로 만들어줌). (인스턴스:실제값, 인덱스, 컬럼명)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["A", "B", "C", "D"])
df

df.head(3) # 앞의 명령한 수만 출력

df.columns # 컬럼명만 출력

df.values # 인스턴스만 출력

df.info() # 테이블 정보 출력

df.describe() # 테이블 상세 정보 및 통계치 출력

df.sort_values(by="B", ascending=False) # 인스턴스 정렬(by="컬럼명", 오름내림차순설정)

df["A"] # 해당컬럼만 출력

df[3:] # 슬라이싱

