# Generated by Django 2.2.5 on 2019-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=64)),
                ('intro', models.CharField(max_length=100)),
                ('userpic', models.FilePathField(path='/img')),
            ],
        ),
    ]
