# Generated by Django 2.2.5 on 2019-11-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userpic',
            field=models.CharField(max_length=100),
        ),
    ]
