# Generated by Django 2.2.5 on 2019-11-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20191105_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='from_id',
            new_name='fromid',
        ),
    ]
