# Generated by Django 2.2.5 on 2019-11-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20191105_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='fromid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='user.User'),
        ),
    ]
