# Generated by Django 2.2.5 on 2019-11-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='img2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='img3',
            field=models.CharField(max_length=100),
        ),
    ]
